[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture arm64",
    "apt-get update -q",
    "apt-get install -y libdbus-1-dev:arm64 curl",
    "curl -fsSL https://github.com/mozilla/sccache/releases/download/v0.15.0/sccache-v0.15.0-x86_64-unknown-linux-musl.tar.gz | tar xz --strip-components=1 -C /usr/local/bin sccache-v0.15.0-x86_64-unknown-linux-musl/sccache",
]
[build.env]
passthrough = [
    "SCCACHE_DIR",
    "RUSTC_WRAPPER",
]
